# Generated by Django 5.0.2 on 2024-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=66)),
                ('author', models.CharField(max_length=66)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
